import { Category, Product, Profile, Order } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-writing',
    name: 'Writing',
    slug: 'writing',
    description: 'Smooth gel pens, ballpoints, and mechanical pencils',
    icon: 'PenTool',
    is_active: true,
    created_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'cat-notebooks',
    name: 'Notebooks',
    slug: 'notebooks',
    description: 'Spiral notebooks, hardcover journals, and grid pads',
    icon: 'BookOpen',
    is_active: true,
    created_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'cat-school',
    name: 'School Supplies',
    slug: 'school-supplies',
    description: 'Rulers, highlighters, erasers, and pencil cases',
    icon: 'GraduationCap',
    is_active: true,
    created_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'cat-office',
    name: 'Office Supplies',
    slug: 'office-supplies',
    description: 'Sticky notes, document folders, and correction tape',
    icon: 'Briefcase',
    is_active: true,
    created_at: '2026-09-01T00:00:00Z',
  },
  {
    id: 'cat-art',
    name: 'Art Supplies',
    slug: 'art-supplies',
    description: 'Drawing graphite pencils, sketchpads, and marker sets',
    icon: 'Highlighter',
    is_active: true,
    created_at: '2026-09-01T00:00:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    category_id: 'cat-writing',
    name: 'Blue Ballpoint Pen (0.7mm)',
    slug: 'blue-ballpoint-pen',
    description: 'Classic oil-based blue ballpoint pen with smooth tungsten carbide ball. Ideal for daily writing, school work, and examinations.',
    price: 1200,
    stock: 58,
    stock_quantity: 58,
    image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Ink Color': 'Archival Blue',
      'Tip Size': '0.7mm Medium',
      'Refillable': 'Yes',
    },
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod-002',
    category_id: 'cat-writing',
    name: 'Black Gel Pen (0.5mm Quick-Dry)',
    slug: 'black-gel-pen',
    description: 'Ultra-smooth roller gel pen with fast-drying, smear-proof black pigment ink. Comfortable non-slip matte grip perfect for everyday note-taking.',
    price: 1500,
    stock: 45,
    stock_quantity: 45,
    image_url: 'https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Ink Color': 'Deep Black',
      'Tip Size': '0.5mm Fine',
      'Drying Speed': '0.5s Quick-Dry',
    },
    created_at: '2026-09-01T11:00:00Z',
  },
  {
    id: 'prod-003',
    category_id: 'cat-writing',
    name: 'Mechanical Pencil (0.5mm Metal Body)',
    slug: 'mechanical-pencil',
    description: 'Weighted precision drafting pencil with diamond knurled metal grip and brass clutch mechanism for break-free lead advancement.',
    price: 3200,
    stock: 24,
    stock_quantity: 24,
    image_url: 'https://images.unsplash.com/photo-1585336261026-41804f5e7c20?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Lead Size': '0.5mm',
      'Material': 'Aluminum Alloy + Solid Brass',
      'Eraser': 'Built-in cap eraser',
    },
    created_at: '2026-09-02T09:00:00Z',
  },
  {
    id: 'prod-004',
    category_id: 'cat-writing',
    name: 'HB Wooden Pencil (Box of 12)',
    slug: 'hb-wooden-pencil',
    description: 'Break-resistant cedarwood HB graphite pencils with soft latex-free pink erasers. Excellent for sketching, school math, and tests.',
    price: 2400,
    stock: 35,
    stock_quantity: 35,
    image_url: 'https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: false,
    specifications: {
      'Lead Grade': 'HB (#2)',
      'Count': '12 Pencils',
      'Wood': 'California Incense Cedar',
    },
    created_at: '2026-09-02T10:30:00Z',
  },
  {
    id: 'prod-005',
    category_id: 'cat-notebooks',
    name: 'A5 Spiral Notebook (Lined 120 Pages)',
    slug: 'a5-spiral-notebook',
    description: 'Durable double-wire copper spiral binding with protective frosted poly cover and 80 GSM bleed-resistant cream paper for smooth writing.',
    price: 2800,
    stock: 42,
    stock_quantity: 42,
    image_url: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Size': 'A5 (148 x 210 mm)',
      'Ruling': '7mm College Ruled',
      'Sheets': '60 Sheets (120 Pages)',
    },
    created_at: '2026-09-03T10:15:00Z',
  },
  {
    id: 'prod-006',
    category_id: 'cat-notebooks',
    name: 'A4 Hardcover Notebook (Grid 160 Pages)',
    slug: 'a4-hardcover-notebook',
    description: 'Luxurious 100 GSM thread-bound grid notebook with linen cloth spine. Opens completely flat 180 degrees. Includes dual bookmark ribbons.',
    price: 6500,
    stock: 18,
    stock_quantity: 18,
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Size': 'A4 (210 x 297 mm)',
      'Grid': '5mm subtle dot grid',
      'Cover': 'Hardcover Fabric Bound',
    },
    created_at: '2026-09-03T14:00:00Z',
  },
  {
    id: 'prod-007',
    category_id: 'cat-office',
    name: 'Pastel Sticky Notes (4 Pads Pack)',
    slug: 'pastel-sticky-notes',
    description: 'Aesthetic Morandi soft pastel sticky notes. High quality water-based adhesive that removes cleanly without leaving paper residue.',
    price: 2500,
    stock: 40,
    stock_quantity: 40,
    image_url: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Size': '76 x 76 mm (3x3 inch)',
      'Count': '4 Pads (80 sheets each)',
      'Colors': 'Sage, Dusty Rose, Butter, Sky Blue',
    },
    created_at: '2026-09-04T09:00:00Z',
  },
  {
    id: 'prod-008',
    category_id: 'cat-school',
    name: 'Pastel Highlighter Set (5 Colors)',
    slug: 'pastel-highlighter-set',
    description: 'Gentle chisel-tip pastel highlighters that mark smoothly without bleeding through textbook pages or overshadowing text.',
    price: 4500,
    stock: 31,
    stock_quantity: 31,
    image_url: 'https://images.unsplash.com/photo-1568205612837-017257d2310a?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Colors': 'Mint, Peach, Lavender, Buttercup, Soft Blue',
      'Tip': 'Dual-angle Soft Chisel',
      'Bleed': 'No bleed on 70+ GSM paper',
    },
    created_at: '2026-09-04T11:00:00Z',
  },
  {
    id: 'prod-009',
    category_id: 'cat-school',
    name: 'Dust-Free Soft Eraser (Pack of 2)',
    slug: 'dust-free-soft-eraser',
    description: 'Non-abrasive polymer eraser that cleans graphite cleanly with minimal shavings that clump together for easy desk cleanup.',
    price: 1000,
    stock: 4, // Low stock (< 10)
    stock_quantity: 4,
    image_url: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: false,
    specifications: {
      'Count': '2 Erasers',
      'Formula': 'Non-toxic, Phthalate-free Polymer',
    },
    created_at: '2026-09-05T08:00:00Z',
  },
  {
    id: 'prod-010',
    category_id: 'cat-school',
    name: '30cm Clear Acrylic Ruler',
    slug: '30cm-clear-acrylic-ruler',
    description: 'Shatter-resistant transparent acrylic ruler with millimeter and centimeter precision etched markings that will not rub off.',
    price: 1200,
    stock: 15,
    stock_quantity: 15,
    image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: false,
    specifications: {
      'Length': '30 cm (12 inches)',
      'Material': 'High-clarity Acrylic',
    },
    created_at: '2026-09-05T09:00:00Z',
  },
  {
    id: 'prod-011',
    category_id: 'cat-school',
    name: 'Canvas Zipper Pencil Case',
    slug: 'canvas-zipper-pencil-case',
    description: 'Multi-layer expandable canvas pouch that holds up to 50 pens and accessories with smooth brass zipper and inner mesh organizer pockets.',
    price: 5500,
    stock: 5, // Low stock (< 10)
    stock_quantity: 5,
    image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Capacity': 'Up to 50 pens',
      'Fabric': '100% Heavy Duty Cotton Canvas',
      'Pockets': 'Dual zipper compartments',
    },
    created_at: '2026-09-06T10:00:00Z',
  },
  {
    id: 'prod-012',
    category_id: 'cat-office',
    name: 'A4 Expanding Document Folder',
    slug: 'a4-expanding-document-folder',
    description: '13-pocket accordion file organizer with colorful index tabs and secure elastic button cord closure for school assignments and receipts.',
    price: 4800,
    stock: 8, // Low stock (< 10)
    stock_quantity: 8,
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: false,
    specifications: {
      'Pockets': '13 Pockets with Color Tabs',
      'Sheet Capacity': 'Up to 350 sheets A4',
    },
    created_at: '2026-09-06T12:00:00Z',
  },
  {
    id: 'prod-013',
    category_id: 'cat-office',
    name: 'Correction Tape (5mm x 6m)',
    slug: 'correction-tape',
    description: 'Instant dry white correction tape with tear-resistant polyester film and swivel applicator tip for clean lines without mess.',
    price: 1800,
    stock: 22,
    stock_quantity: 22,
    image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: false,
    specifications: {
      'Tape Width': '5 mm',
      'Tape Length': '6 meters',
      'Dry Time': 'Instant',
    },
    created_at: '2026-09-07T14:00:00Z',
  },
  {
    id: 'prod-014',
    category_id: 'cat-art',
    name: 'Dual Tip Art Marker Set (12 Colors)',
    slug: 'dual-tip-art-marker-set',
    description: 'Dual-ended brush and chisel tip markers for sketching, bullet journaling, and hand lettering. Vibrant blendable alcohol-free ink.',
    price: 12500,
    stock: 6, // Low stock (< 10)
    stock_quantity: 6,
    image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
    is_active: true,
    featured: true,
    specifications: {
      'Count': '12 Color Pens',
      'Tips': 'Flexible Brush + 3mm Chisel',
    },
    created_at: '2026-09-07T16:00:00Z',
  },
];

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'user-demo-customer',
    email: 'customer@example.com',
    full_name: 'Su Myat Noe',
    phone: '09 798 123 456',
    address: 'No. 42, Inya Road, Kamayut Township, Yangon',
    role: 'customer',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'user-demo-admin',
    email: 'admin@example.com',
    full_name: 'Inkora Administrator',
    phone: '09 977 888 999',
    address: 'Inkora Stationery HQ, Bogyoke Aung San Road, Yangon',
    role: 'admin',
    created_at: '2026-09-01T08:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-001',
    order_number: 'INK-202609-001',
    user_id: 'user-demo-customer',
    total_amount: 14500,
    status: 'completed',
    customer_name: 'Su Myat Noe',
    phone: '09 798 123 456',
    delivery_address: 'No. 42, Inya Road, Kamayut Township, Yangon',
    payment_method: 'cod',
    created_at: '2026-09-24T14:30:00Z',
    updated_at: '2026-09-26T10:00:00Z',
    items: [
      {
        id: 'item-001',
        order_id: 'ord-001',
        product_id: 'prod-001',
        product_name: 'Blue Ballpoint Pen (0.7mm)',
        price: 1200,
        quantity: 5,
        subtotal: 6000,
        image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'item-002',
        order_id: 'ord-001',
        product_id: 'prod-006',
        product_name: 'A4 Hardcover Notebook (Grid 160 Pages)',
        price: 6500,
        quantity: 1,
        subtotal: 6500,
        image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'item-003',
        order_id: 'ord-001',
        product_id: 'prod-009',
        product_name: 'Dust-Free Soft Eraser (Pack of 2)',
        price: 1000,
        quantity: 2,
        subtotal: 2000,
        image_url: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    id: 'ord-002',
    order_number: 'INK-202609-002',
    user_id: 'user-demo-customer',
    total_amount: 11000,
    status: 'processing',
    customer_name: 'Kyaw Zin Htet',
    phone: '09 445 678 901',
    delivery_address: 'Room 3B, Pearl Condo, Bahan Township, Yangon',
    payment_method: 'cod',
    created_at: '2026-09-26T09:15:00Z',
    updated_at: '2026-09-26T11:00:00Z',
    items: [
      {
        id: 'item-004',
        order_id: 'ord-002',
        product_id: 'prod-002',
        product_name: 'Black Gel Pen (0.5mm Quick-Dry)',
        price: 1500,
        quantity: 3,
        subtotal: 4500,
        image_url: 'https://images.unsplash.com/photo-1569683795645-b62e50fbf103?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'item-005',
        order_id: 'ord-002',
        product_id: 'prod-008',
        product_name: 'Pastel Highlighter Set (5 Colors)',
        price: 4500,
        quantity: 1,
        subtotal: 4500,
        image_url: 'https://images.unsplash.com/photo-1568205612837-017257d2310a?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'item-006',
        order_id: 'ord-002',
        product_id: 'prod-009',
        product_name: 'Dust-Free Soft Eraser (Pack of 2)',
        price: 1000,
        quantity: 2,
        subtotal: 2000,
        image_url: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
  {
    id: 'ord-003',
    order_number: 'INK-202609-003',
    user_id: null,
    total_amount: 18000,
    status: 'pending',
    customer_name: 'Thandar Aung',
    phone: '09 250 112 233',
    delivery_address: 'Building 14, Hledan Station Road, Kamayut, Yangon',
    payment_method: 'cod',
    created_at: '2026-09-28T08:20:00Z',
    updated_at: '2026-09-28T08:20:00Z',
    items: [
      {
        id: 'item-007',
        order_id: 'ord-003',
        product_id: 'prod-014',
        product_name: 'Dual Tip Art Marker Set (12 Colors)',
        price: 12500,
        quantity: 1,
        subtotal: 12500,
        image_url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=600&q=80',
      },
      {
        id: 'item-008',
        order_id: 'ord-003',
        product_id: 'prod-011',
        product_name: 'Canvas Zipper Pencil Case',
        price: 5500,
        quantity: 1,
        subtotal: 5500,
        image_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=600&q=80',
      },
    ],
  },
];
